In [1]:
## numpy basic 

In [2]:
import numpy as np
import time

### create simple array using numpy 

In [3]:
arr = np.array([1,2,3,4,5]) # createing array for list
print(f"one d array : {arr}")

arr_2d = np.array([[1,2,3],[4,5,6]])
print(f"two d array : {arr_2d}")

one d array : [1 2 3 4 5]
two d array : [[1 2 3]
 [4 5 6]]


### list vs array

In [4]:
py_list = [1, 2, 3]
print("python list multiplication : ",py_list * 2)

np_array = np.array([1, 2, 3]) # element wise multiplication
print("numpy array  multiplication : ",np_array * 2)

python list multiplication :  [1, 2, 3, 1, 2, 3]
numpy array  multiplication :  [2 4 6]


In [5]:
start = time.time()
py_list = [i*2 for i in range(1000000)]
# print(py_list)
print("list opration time",time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
# print(np_array)
print("numpy opration time",time.time() - start)

list opration time 0.0986337661743164
numpy opration time 0.011084794998168945


### creating array from scratch

In [6]:
zeros = np.zeros((3,4))
print("zeros array : \n",zeros)

ones = np.ones((2,3))
print("ones array : \n",ones)

full = np.full((2,2),7)
print("full array : \n",full)

random = np.random.random((2,3))
print("random array : \n",random)

sequence = np.arange(0,10,2)
print("sequence array : \n",sequence)

zeros array : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array : 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array : 
 [[7 7]
 [7 7]]
random array : 
 [[0.7603413  0.79489207 0.86579388]
 [0.58553845 0.44530438 0.73959239]]
sequence array : 
 [0 2 4 6 8]


### vector,matrix and tensor

In [7]:
vector = np.array([1,2,3])
print("vector : ",vector)

matrix = np.array([[1,2,3],
                   [3,4,5]])
print("matrix : \n",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor : \n",tensor)

vector :  [1 2 3]
matrix : 
 [[1 2 3]
 [3 4 5]]
tensor : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties

In [8]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("Shape : ",arr.shape) # it is return to rows and column 
print("Dimension :",arr.ndim)  # return to dimension
print("size : ",arr.size) # return to size of array
print("dtype : ",arr.dtype) # return data type

Shape :  (2, 3)
Dimension : 2
size :  6
dtype :  int64


### Array Reshaping

In [9]:
arr = np.arange(12)
print("Orignal array : ",arr)

# reshape **

reshaped = arr.reshape((3,4))
print("reshaped array : \n",reshaped)

flattened = reshaped.flatten() # return copy of array
print("flattened array : ",flattened)

reveled = reshaped.ravel() # return orignal array
print("reveled array : ",reveled)

# transpose

transpose = reshaped.T
print("transpose : \n",transpose)

Orignal array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
reveled array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
