### numpy array opration and 

In [14]:
import numpy as np

In [15]:
arr = np.arange(11)
print("basic array : ",arr)

basic array :  [ 0  1  2  3  4  5  6  7  8  9 10]


### basic slicing

In [ ]:
print("Basic Slicing : ",arr[2:7])
print("With Stap : ",arr[2:10:2])
print("Nagative Indexing : ",arr[-3])
print("slicing to step of element : ",arr[2:8:2]) # [start:end:step].

Basic Slicing :  [3 4 5]
With Stap :  [3 5]
Nagative Indexing :  3
slicing to step of element :  [3 5]


In [17]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# slicing in 2d array 
print("Specific element",arr_2d[1][2])
# ********** or ***********
print("Specific element : ",arr_2d[1,2])
print("Entire row : ",arr_2d[1])
print("Entire column : ",arr_2d[:,1]) # : it is use to all row 
print("Entire row select and column sliceing : ",arr_2d[1,1:3]) 
print("Entire column select and row sliceing",arr_2d[1:3,1])
print("Entire column sliceing and row sliceing \n",arr_2d[1:3,0:3])

Specific element 6
Specific element :  6
Entire row :  [4 5 6]
Entire column :  [2 5 8]
Entire row select and column sliceing :  [5 6]
Entire column select and row sliceing [5 8]
Entire column sliceing and row sliceing 
 [[4 5 6]
 [7 8 9]]


### sorting

In [18]:
unsorted = np.array([3,5,1,4,7,9,8,2])
print("sort array : ",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("sorted 2d array row : \n",np.sort(arr_2d_unsorted,axis=0)) # sort data in row wise
print("sorted 2d array column : \n",np.sort(arr_2d_unsorted,axis=1)) # sort daya in column wise

sort array :  [1 2 3 4 5 7 8 9]
sorted 2d array row : 
 [[1 1]
 [2 2]
 [3 3]]
sorted 2d array column : 
 [[1 3]
 [1 2]
 [2 3]]


### filter

In [19]:
numbers = np.arange(1,11)
print(numbers)

even_number = numbers[numbers % 2 == 0] # condition pass ans condition true and return array elament
# it is same to np.where()
print("Even number : ",even_number)

[ 1  2  3  4  5  6  7  8  9 10]
Even number :  [ 2  4  6  8 10]


### filter with mask

In [20]:
mask = numbers > 5
print("numbers grater then five ",numbers[mask]) # condition pass ans condition true and return array elament

numbers grater then five  [ 6  7  8  9 10]


### fancy indexing vs np.where()

In [28]:
indexing = [0,2,4] # index store
print(indexing) # store index in indexing variable and print
print(numbers[indexing]) # indexing pass and index value return
print(numbers[[1,4,6]])

# condition pass to array and return true array elament
where_result = np.where(numbers > 5) # it is same to filter mask and 
print(where_result) # where_result store index 
print("Np where",numbers[where_result])

[0, 2, 4]
[1 3 5]
[2 5 7]
(array([5, 6, 7, 8, 9]),)
Np where [ 6  7  8  9 10]


In [22]:
condition_array = np.where(numbers > 5,numbers*2,numbers)
# condition_array = np.where(condition, x(true), y(false))
# If number > 5 → multiply by 2
# Else → keep the same number
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


### adding and removing data

In [23]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2)) 
print(combined)

[1 2 3 4 5 6]


### array compatibilty

In [24]:
a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([7,8,9])

print("Comatibility shape",a.shape == b.shape)
print("Comatibility shape",a.shape == c.shape)

Comatibility shape False
Comatibility shape True


In [25]:
original = np.array([[1 , 2],[3 , 4]])
new_row = np.array([[5 , 6]])

# vstack is add to row
with_new_row = np.vstack((original,new_row))
print("add new row :\n",with_new_row)

# hstack is add to column
new_column = np.array([[7],[8]])
with_new_col = np.hstack((original,new_column))
print("add new column :\n",with_new_col)

add new row :
 [[1 2]
 [3 4]
 [5 6]]
add new column :
 [[1 2 7]
 [3 4 8]]


### removeing

In [ ]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,3)
print("array after deleted : ",deleted) # return to array all element after deleted value

array after deleted :  [1 2 3 5]
