In [55]:
import numpy as np

In [56]:
arr = np.arange(5,dtype=np.uint8)
print(arr)

[0 1 2 3 4]


In [57]:
a = np.array([1,2,3],dtype='f') #  float32
# a = np.array([1,2,3],dtype=np.float32)  
print(a) ## float32

b = np.array([4,5,6],dtype='d')
# b = np.array([4,5,6],dtype=np.float64)
print(b) # float64

c = b.astype(np.int64) # change datatype
print(c)

[1. 2. 3.]
[4. 5. 6.]
[4 5 6]


In [58]:
arr = np.arange(3,dtype=np.float64)
np.issubdtype(arr.dtype,np.integer) # False
np.issubdtype(arr.dtype,np.floating) # True

True

In [70]:
# string 
arrStr = np.array(["hello","world"],dtype='<U6')
print(arrStr)
print(arrStr.dtype) # max to 6 code long

arrStr2 = np.array(['hello','world'],dtype='U5')
print(arrStr2)
arrStr2 = np.array(['hello','world'],dtype='U7')
print(arrStr2)


['hello' 'world']
<U6
['hello' 'world']
['hello' 'world']
